FROM ubuntu:20.04

ARG PLATFORM="mac"

# Update packages & install native dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     curl gnupg build-essential ca-certificates git

 # Install node js
RUN apt-get update \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y --no-install-recommends \
      nodejs

RUN npm install -g yarn

# Create app directory
RUN mkdir -p /pocket-wallet/build-native

WORKDIR /pocket-wallet/
VOLUME /pocket-wallet/build-native

# Install app dependencies
COPY package.json /pocket-wallet/
RUN yarn

# Bundle app source
COPY . /pocket-wallet/

ENTRYPOINT ["yarn"]
CMD ["run", "build-native-mac"]
