FROM electronuserland/builder:latest

# Create app directory
RUN mkdir -p /pocket-wallet
RUN mkdir -p /pocket-wallet/build-native

RUN npm install -g yarn

WORKDIR /pocket-wallet/
VOLUME /pocket-wallet/build-native

# Install app dependencies
COPY package.json /pocket-wallet/
COPY yarn.lock /pocket-wallet/
RUN yarn

# Bundle app source
COPY . /pocket-wallet/

ENTRYPOINT ["yarn"]
CMD ["run", "pack-native-linux"]
